### ISSUE TITLE
Audio toggle

### ISSUE THREAD

**Issue by tomekwes** [instantOS/instantASSIST#7]
Audio toggle doesn't work for me. 
Fixed it with 
`|| amixer -D pulse set 'Master' toggle`
appended to file utils/p.sh line 28

**Comment by con-f-use** [comment]
Huh? Line 28 already says that.

[For reference](https://github.com/instantOS/instantASSIST/blob/master/utils/p.sh#L28): `amixer -D pulse set 'Master' toggle`

**Comment by tomekwes** [comment]
My bad, didn't check the repo only my local file. installed os on staturday and i guess it had older version
